version: 2
jobs:
  build:
    working_directory: ~/nancy
    docker:
      - image: node:8.2
    steps:
      - checkout
      - run: Tests
        command: |
          for f in tests/*.sh; do bash "$f" -H; done
