version: 2
jobs:
  build:
    working_directory: ~/nancy
    docker:
      - image: node:8.2
    steps:
      - checkout
      - run:
          name: Tests
          command: |
            for f in tests/*.sh; do printf "$f\t\t" && bash "$f" -H; done
