version: 2
jobs:
  build:
    working_directory: ~/nancy
    docker:
      - image: node:8.2
    steps:
      - run:
          name: Install software
          command: |
            apt-get install -y sudo \
            && apt-get install -y apt-transport-https ca-certificates curl software-properties-common \
            && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - \
            && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
            && apt-get update && apt-get install docker-ce
      - checkout
      - run:
          name: Tests
          command: |
            errcount=0; for f in tests/*.sh; do printf "$f\t\t" && bash "$f" -H; \
              status=$? && [ $status -ne 0 ] && errcount="$(($errcount+1))"; done; \
              [ $errcount -ne 0 ] && >&2 echo -e "Oh no! $errcount tests failed" && exit 1
