version: 2
jobs:
  build:
    working_directory: ~/nancy
    docker:
      - image: ubuntu:16.04
    steps:
      - run:
          name: Install software
          command: |
            apt-get update && apt-get install -y sudo wget \
            && wget get.docker.com -q -S -O - | sudo sh
      - checkout
      - run:
          name: Tests
          command: |
            errcount=0; for f in tests/*.sh; do printf "$f\t\t" && bash "$f" -H; \
              status=$? && [ $status -ne 0 ] && errcount="$(($errcount+1))"; done;
              #[ $errcount -ne 0 ] && echo -e "Oh no! $errcount tests failed"
              #[ $errcount -ne 0 ] && exit 1

